### ISSUE TITLE
Getting an error of redeclaration.

### ISSUE THREAD

**Issue by rennymroy** [dmitriybelyy/yii2-cassandra-cql#1]
I tried to connect cassandra with Yii 2.

Copied below code in config/web.php.
  'cassandra' => [
        'class' => '\beliy\cassandra\Connection',
        'keyspace' => 'youkeyspace',
        'servers' => ['127.0.0.1', ...],
    ],
    'cache' => [
      'class' => '\beliy\cassandra\Cache',
      'tableName' => 'cache', // dedault 'cache'
      'tablePrefix' => 'mega', // default ''
    ],

When I tried to run the code $cass = Yii::$app->cassandra;. I am getting "Cannot redeclare class cassandra\Column". Please help me in this issue. Thank you

**Comment by dmitriybelyy** [comment]
Please do not use this **deprecated** component based on phpcassa.
You can write simple wrapper for Yii2 over native driver https://github.com/datastax/php-driver

The cause of the error namespace conflict with native driver (cassandra.so) has the same namespace as Cassandra.php Thrift.
